# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.2

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - apt-get update
          - apt-get install -y maven 
          - npm install -g webpack@4.29.5 webpack-dev-server@3.2.1 bower@1.8.8 babel-core@^7
          - npm install
          - webpack
          - mvn install
